- name: app setup
  include_role:
    name: common
    tasks_from: app-setup.yaml
- name: nodejs setup
  include_role:
    name: common
    tasks_from: nodejs.yaml

- name: system service
  include_role:
    name: common
    tasks_from: systemd.yaml
