- name: disabling nginx
  ansible.builtin.command: dnf module disable nginx -y

- name: enabling nginx
  ansible.builtin.command: dnf module enable nginx:1.24 -y

- name: installing nginx
  ansible.builtin.package:
    name: nginx
    state: installed

- name: start and enable nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: remove existing html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: create html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: download frontend content
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /tmp/frontend.zip

- name: extract frontend content
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: copy nginx configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
   - Restart nginx

