- name: configuring mysql server
  hosts: mysql
  become: yes
  tasks:
   - name: installing mysql
     ansible.builtin.dnf: 
       name: mysql-server
       state: installed
   - name: start and enable mysql server -y
     ansible.builtin.service:
       name: mysqld
       enabled: yes
       state: started

   - name: setup root password
     ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1
   
       
