- name: disabling nodejs
  ansible.builtin.command: dnf module disable nodejs -y
- name: enable nodejs
  ansible.builtin.command: dnf module disable nodejs:20 -y
- name: installing nodejs
  ansible.builtin.dnf:
    name: nodejs 
    state: present
- name: creating user
  ansible.builtin.user:
    name: roboshop
    shell: /sbin/nologin
    home: /app
- name: creating app folder
  ansible.builtin.file:
    path: /app
    state: directory
- name: downloading the content
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
    dest: /tmp/catalogue.zip
- name: extracting a file 
  ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes    #means that already file exists in catalogue server

- name: installing dependencies
  community.general.npm:
    path: /app
    state: present
- name: copy catalogue service
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service
- name: systemctl daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true
- name: start and enable service
  ansible.builtin.service:
    name: catalogue
    state: started
    enabled: yes
- name: copy mongod repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo
- name: install mongodb client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: installed

- name: check products load or not
  ansible.builtin.shell: mongosh --host 172.31.70.137 --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: catalogue_output

- name: print the output
  ansible.builtin.debug:
    msg: "{{ catalogue_output }}"

- name: load the products
  ansible.builtin.shell: mongosh --host 172.31.70.137 </app/db/master-data.js
  when: catalogue_output.stdout | int < 0


    
