- name: creating app folder
  ansible.builtin.file:
    path: /app
    state: directory
- name: creating user
  ansible.builtin.user:
    name: roboshop
    shell: /sbin/nologin
    home: /app

- name: downloading the content
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip 
    dest: /tmp/{{ component }}.zip
- name: extracting a file 
  ansible.builtin.unarchive:
      src: /tmp/{{ component }}.zip
      dest: /app
      remote_src: yes    