- name: installing maven and mysql
  ansible.builtin.dnf:
   name: "{{ item }}"
   state: installed
  loop:
   - mysql
   - maven
- name: installing PyMySQL and cryptography
  ansible.builtin.pip:
   name: "{{ item }}"
   executable: pip3.9
  loop:
  - PyMySQL
  - cryptography
- name: installing dependencies
  ansible.builtin.command: mvn clean package 
  args:
    chdir: /app
- name: renaming jar file
  ansible.builtin.command: mv target/{{ component }}-1.0.jar {{  component }}.jar 
  args:
    chdir: /app
